# Generated by Django 2.1.1 on 2018-10-02 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceCheckboxQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceRadioQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=200)),
                ('question_desc', models.CharField(max_length=500)),
                ('question_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_desc', models.CharField(max_length=500)),
                ('survey_create_date', models.DateField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='FreeFormQuestion',
            fields=[
                ('questiontype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paranoidApp.QuestionType')),
            ],
            bases=('paranoidApp.questiontype',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceCheckboxQuestion',
            fields=[
                ('questiontype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paranoidApp.QuestionType')),
            ],
            bases=('paranoidApp.questiontype',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceRadioQuestion',
            fields=[
                ('questiontype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paranoidApp.QuestionType')),
            ],
            bases=('paranoidApp.questiontype',),
        ),
        migrations.AddField(
            model_name='questiontype',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paranoidApp.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paranoidApp.Survey'),
        ),
        migrations.AddField(
            model_name='multiplechoiceradioquestionanswer',
            name='parent_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paranoidApp.MultipleChoiceRadioQuestion'),
        ),
        migrations.AddField(
            model_name='multiplechoicecheckboxquestionanswer',
            name='parent_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paranoidApp.MultipleChoiceCheckboxQuestion'),
        ),
    ]
