# Generated by Django 2.1.1 on 2018-10-02 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paranoidApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanQuestion',
            fields=[
                ('questiontype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paranoidApp.QuestionType')),
            ],
            bases=('paranoidApp.questiontype',),
        ),
        migrations.CreateModel(
            name='NumericalQuestion',
            fields=[
                ('questiontype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paranoidApp.QuestionType')),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField()),
            ],
            bases=('paranoidApp.questiontype',),
        ),
    ]
